### ISSUE TITLE
WARNING:  RXTX Version mismatch

### ISSUE THREAD

**Issue by HeroErix** [digidotcom/XBeeJavaLibrary#120]
I have followed the instructions for Getting started with XBee Java Library here: https://www.digi.com/resources/documentation/digidocs/90001438/Default.htm

When attempting to run the example program in eclipse I get the following output.
![xbee example error](https://user-images.githubusercontent.com/31548922/37615014-a1846050-2b82-11e8-86cd-6c90480874be.png)
And the receiver will receive what is shown no matter what message I try to send.
![2018-03-19 14_33_25-](https://user-images.githubusercontent.com/31548922/37615015-a195fcb6-2b82-11e8-9f24-7fc144af3b25.png)

I have previously used these two devices to communicate, the sender connected to XCTU and the receiver connected to an arduino, so the settings on each device should be correct. Any help in solving these errors would be appreciated.

**Comment by hgonzaleDigi** [comment]
It seems that your local device is working in AT mode. This library only supports "API" and "API with escapes" operating modes.
So, in order to use this library, verify the AP setting of your local device reports values of 1 or 2.

**Comment by HeroErix** [comment]
Thank you. I changed both devices to API mode and I can now send using the example application.
