### ISSUE TITLE
Support AO=3?

### ISSUE THREAD

**Issue by joychen130** [digidotcom/XBeeJavaLibrary#26]
I have a question. Is this library have plan to support explicit with ZDO frame API mode? That will help me use ZB S2 module to talk with other standard Zigbee device. Thanks.

**Comment by tatianaleon** [comment]
Hi @joychen130, 

We have just released a new version of the library (1.1.0) that includes support for explicit frames (AO=1, AO=3).

Have a look at https://github.com/digidotcom/XBeeJavaLibrary/releases/tag/v1.1.0

Regards
