### ISSUE TITLE
New version in Maven

### ISSUE THREAD

**Issue by jetremote** [digidotcom/XBeeJavaLibrary#45]
Hello,

Could you update Maven to the version 1.1.0?

Best regards

**Comment by posborne** [comment]
Hi @jetremote, I'll try to get a new version published in the next couple of days.  Sorry about the delay.  Longer term, we'll try to get something in place so it happens in a more timely fashion.

**Comment by jetremote** [comment]
Thank you,

Best regards

**Comment by jon-whit** [comment]
I'd like to bump this request. It would be nice if Digi would get this project loaded into the [Maven central repository][1]. I'm just starting to use this library on a project of mine, and I'd like to use Maven for my dependency management.

[1]: http://search.maven.org/

**Comment by rhwood** [comment]
Will this library be available from maven?

**Comment by rubenmoral** [comment]
We'll try to upload the library to Maven Central soon, I have created a task for this. We'll keep you updated on our progress in #32.
