### ISSUE TITLE
Comunicate Android device with XBee Wifi

### ISSUE THREAD

**Issue by jetremote** [digidotcom/XBeeJavaLibrary#47]
Hello,

I'm working on a new project for opening garage doors and need to communicate a Android smartphone with a wireless XBee module.

http://www.digi.com/products/xbee-rf-solutions/modules/xbee-wi-fi

¿XBeeJavaLibrary is required  or WifiManager enough?

http://developer.android.com/reference/android/net/wifi/WifiManager.html

Other question: XBee Wifi support P2P (Wifi Direct) ?

Best regards

**Comment by rubenmoral** [comment]
Hi @jetremote,

The XBee Java Library does not support XBee WiFi modules and there's no plan to support them for now.

Sorry for the inconveniences.
